#application
server:
  port: 50900
  tomcat.threads.max: 20
  forward-headers-strategy: FRAMEWORK

#monitoring
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,prometheus,heapdump"

#persistence
spring.jpa.hibernate.ddl-auto: "none"
spring.datasource.url: jdbc:h2:mem:masterdata;MODE=POSTGRESQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=VALUE
#spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres

spring.datasource.hikari.maximum-pool-size: "10"
spring.datasource.hikari.connection-timeout: "10000"

#mongo
spring.data.mongodb.username: mongodb
spring.data.mongodb.password: mongodb
spring.data.mongodb.authentication-database: admin
spring.data.mongodb.database: core

#jobrunr
org.jobrunr.background-job-server.enabled: "true"
org.jobrunr.dashboard.enabled: "true"
org.jobrunr.dashboard.port: "8001"

org.jobrunr.database.skip-create: "true" #may be needed for flyway to be turned on and use jobrunr sqls on your own
org.jobrunr.database.table-prefix: "masterdata."
spring.flyway.default-schema: "masterdata"

#logging
logging.pattern.level: "%5p tenantId=%X{tenantId:-}" #"%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] tenantId=%X{tenantId:-}"

logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

#profile
spring.profiles.active: "jdbc" #mongodb
